name: php-pkcs11 using SoftHSM2 CI

on:
  # Triggers the workflow on push or pull requests events for any branch
  push:
  pull_request:
  # Everey night of from Monday to Friday
  schedule:
    - cron: "0 2 * * 1-5"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  SOFTHSM2_TOKENDIR: /tmp/php-pkcs11-softhsm
  SOFTHSM2_CONF: /tmp/php-pkcs11-softhsm2.conf
  PHP11_PIN: 123456
  PHP11_SOPIN: 12345678

jobs:
  # This workflow contains a single job called "build"
  test-with-php-7_4:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Installing packages
        run: sudo apt-get install php7.4-dev softhsm2 pkcs11-dump 

      - name: Setup Ubuntu SoftHSM2
        run: |
          export PHP11_MODULE=/usr/lib/softhsm/libsofthsm2.so
          mkdir -p $SOFTHSM2_TOKENDIR
          cat <<EOFCONF >> $SOFTHSM2_CONF
          directories.tokendir = $SOFTHSM2_TOKENDIR
          objectstore.backend = file
          log.level = INFO
          slots.removable = false
          slots.mechanisms = ALL
          EOFCONF
          softhsm2-util --init-token --slot 0 --label "Test Token" --pin $PHP11_PIN --so-pin $PHP11_SOPIN
          pkcs11-dump info $PHP11_MODULE
          pkcs11-dump slotlist $PHP11_MODULE

      - name: Compile
        run: |
          phpize
          ./configure
          make -j $(nproc)

      - name: Tests using SoftHSM2
        run: |
          export PHP11_MODULE=/usr/lib/softhsm/libsofthsm2.so
          echo "PHP11_MODULE $PHP11_MODULE"
          export PHP11_SLOT=$(pkcs11-dump slotlist $PHP11_MODULE 2>/dev/null | grep SoftHSM | head -1 | cut -f 1)
          echo "PHP11_SLOT $PHP11_SLOT"
          export NO_INTERACTION=1
          export REPORT_EXIT_STATUS=1
          make test

  test-with-php-8_0:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Installing packages
        run: sudo apt-get install php8.0-dev softhsm2 pkcs11-dump 

      - name: Setup Ubuntu SoftHSM2
        run: |
          export PHP11_MODULE=/usr/lib/softhsm/libsofthsm2.so
          mkdir -p $SOFTHSM2_TOKENDIR
          cat <<EOFCONF >> $SOFTHSM2_CONF
          directories.tokendir = $SOFTHSM2_TOKENDIR
          objectstore.backend = file
          log.level = INFO
          slots.removable = false
          slots.mechanisms = ALL
          EOFCONF
          softhsm2-util --init-token --slot 0 --label "Test Token" --pin $PHP11_PIN --so-pin $PHP11_SOPIN
          pkcs11-dump info $PHP11_MODULE
          pkcs11-dump slotlist $PHP11_MODULE

      - name: Compile
        run: |
          phpize
          ./configure
          make -j $(nproc)

      - name: Tests using SoftHSM2
        run: |
          export PHP11_MODULE=/usr/lib/softhsm/libsofthsm2.so
          echo "PHP11_MODULE $PHP11_MODULE"
          export PHP11_SLOT=$(pkcs11-dump slotlist $PHP11_MODULE 2>/dev/null | grep SoftHSM | head -1)
          echo "PHP11_SLOT $PHP11_SLOT"
          export NO_INTERACTION=1
          make test
